# postgres + CeleryExecutor
services:
  postgres:
    image: postgres:16
    container_name: airflow-postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: airflow-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
 
  # Einmaliger Init-Job für Migration & Admin-User
  airflow-init:
    image: my-airflow:2.9.2
    depends_on:
      postgres: { condition: service_healthy }
      redis: { condition: service_healthy }
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
      - AIRFLOW__CORE__EXECUTOR=${AIRFLOW__CORE__EXECUTOR}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CELERY__BROKER_URL=${AIRFLOW__CELERY__BROKER_URL}
      - AIRFLOW__CELERY__RESULT_BACKEND=${AIRFLOW__CELERY__RESULT_BACKEND}
      - _PIP_ADDITIONAL_REQUIREMENTS=pandas>=2.2 numpy>=2,<3 scikit-learn>=1.4,<2 scipy>=1.11 psycopg2-binary redis matplotlib
    #user: "${AIRFLOW_UID:-50000}:0"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./models:/opt/airflow/models
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
    entrypoint: ["bash","-lc"]
    command: >
      "airflow db migrate &&
       airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true"

  airflow-webserver:
    image: my-airflow:2.9.2
    container_name: airflow-web
    depends_on:
      postgres: { condition: service_healthy }
      redis: { condition: service_healthy }
      airflow-init: { condition: service_completed_successfully }
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
      - AIRFLOW__CORE__EXECUTOR=${AIRFLOW__CORE__EXECUTOR}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE=Europe/Zurich
      - AIRFLOW__CELERY__BROKER_URL=${AIRFLOW__CELERY__BROKER_URL}
      - AIRFLOW__CELERY__RESULT_BACKEND=${AIRFLOW__CELERY__RESULT_BACKEND}
      - _PIP_ADDITIONAL_REQUIREMENTS=pandas>=2.2 numpy>=2,<3 scikit-learn>=1.4,<2 scipy>=1.11 psycopg2-binary redis matplotlib
    user: "${AIRFLOW_UID:-50000}:0"
    ports: ["8080:8080"]
    volumes:
      - ./dags:/opt/airflow/dags
      - ./models:/opt/airflow/models
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
    command: webserver

  airflow-scheduler:
    image: my-airflow:2.9.2
    container_name: airflow-scheduler
    depends_on:
      postgres: { condition: service_healthy }
      redis: { condition: service_healthy }
      airflow-init: { condition: service_completed_successfully }
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
      - AIRFLOW__CORE__EXECUTOR=${AIRFLOW__CORE__EXECUTOR}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CELERY__BROKER_URL=${AIRFLOW__CELERY__BROKER_URL}
      - AIRFLOW__CELERY__RESULT_BACKEND=${AIRFLOW__CELERY__RESULT_BACKEND}
      - _PIP_ADDITIONAL_REQUIREMENTS=pandas>=2.2 numpy>=2,<3 scikit-learn>=1.4,<2 scipy>=1.11 psycopg2-binary redis matplotlib
      - LLM_PROVIDER=openai
      - LLM_ENDPOINT=https://api.openai.com/v1/chat/completions
      - LLM_MODEL=gpt-4o-mini
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    user: "${AIRFLOW_UID:-50000}:0"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./models:/opt/airflow/models
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
    command: scheduler

  airflow-worker:
    image: my-airflow:2.9.2
    container_name: airflow-worker
    depends_on:
      postgres: { condition: service_healthy }
      redis: { condition: service_healthy }
      airflow-init: { condition: service_completed_successfully }
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
      - AIRFLOW__CORE__EXECUTOR=${AIRFLOW__CORE__EXECUTOR}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CELERY__BROKER_URL=${AIRFLOW__CELERY__BROKER_URL}
      - AIRFLOW__CELERY__RESULT_BACKEND=${AIRFLOW__CELERY__RESULT_BACKEND}
      - _PIP_ADDITIONAL_REQUIREMENTS=pandas>=2.2 numpy>=2,<3 scikit-learn>=1.4,<2 scipy>=1.11 psycopg2-binary redis matplotlib
      - LLM_PROVIDER=openai
      - LLM_ENDPOINT=https://api.openai.com/v1/chat/completions
      - LLM_MODEL=gpt-4o-mini
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    user: "${AIRFLOW_UID:-50000}:0"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./models:/opt/airflow/models
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
    command: celery worker