channels:
- conda-forge
dependencies:
- python=3.12.4
- pip<=24.0
- pip:
  - mlflow==2.14.1
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - packaging==24.0
  - pandas==2.2.2
  - psutil==5.9.8
  - pyyaml==6.0.1
  - scikit-learn==1.4.2
  - scipy==1.11.4
  - xgboost==2.1.1
name: mlflow-env
