apiVersion: 1
datasources:
  - name: Airflow Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: airflow
    user: airflow
    secureJsonData:
      password: airflow
    jsonData:
      sslmode: disable
      timescaledb: false