name: Update metrics.json (daily)

on:
  workflow_dispatch: {}
  schedule:
    # Täglich 03:05 UTC (Sommer: 05:05 CH, Winter: 04:05)
    - cron: "5 3 * * *"

permissions:
  contents: write

concurrency:
  group: pages-metrics
  cancel-in-progress: false

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Setup SSH key & known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          # Host key pinning (nimm den ed25519-Key deiner VM-IP)
          cat >> ~/.ssh/known_hosts <<'EOF'
          34.65.44.185 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBfFzZbf7u5wzJqSW+RtHGr02Nh8MxDnVDjL0H0Cvtj9
          EOF
          chmod 644 ~/.ssh/known_hosts

      - name: Run export on VM
        env:
          VM_HOST: ${{ secrets.VM_HOST }}
          VM_USER: ${{ secrets.VM_USER }}
        run: |
          set -eo pipefail
          ssh -i ~/.ssh/id_ed25519 "${VM_USER}@${VM_HOST}" bash -lc '
            set -eo pipefail
            cd ~/mlops-spam-gcp
            # (optional) venv nutzen
            if [ -f .venv/bin/activate ]; then . .venv/bin/activate; fi
            # DSN für Postgres-Container, der auf der VM auf 5432 published ist:
            export METRICS_PG_DSN="postgresql://airflow:airflow@127.0.0.1:5432/airflow_prod"
            python3 tools/export_metrics_for_pages.py
            echo "[VM] Created:"
            ls -lh docs/metrics.json || true
          '

      - name: Copy metrics.json from VM
        env:
          VM_HOST: ${{ secrets.VM_HOST }}
          VM_USER: ${{ secrets.VM_USER }}
        run: |
          set -eo pipefail
          scp -i ~/.ssh/id_ed25519 "${VM_USER}@${VM_HOST}:~/mlops-spam-gcp/docs/metrics.json" ./metrics.json
          test -f ./index.html || echo "<h1>placeholder</h1>" > index.html
          ls -lh metrics.json

      - name: Commit & push if changed (gh-pages)
        run: |
          set -eo pipefail
          if ! git diff --quiet -- metrics.json; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add metrics.json
            git commit -m "metrics: daily auto-update"
            git push origin gh-pages
          else
            echo "No changes in metrics.json"
          fi
