name: Update metrics.json (daily)

on:
  workflow_dispatch: {}
  schedule:
    # Täglich 03:05 UTC (entspricht 05:05 in CH im Sommer, 04:05 im Winter)
    - cron: "5 3 * * *"

permissions:
  contents: write

concurrency:
  group: pages-metrics
  cancel-in-progress: false

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install ssh client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "${{ secrets.VM_HOST }}" >> ~/.ssh/known_hosts

      - name: Run export script on VM
        env:
          VM_HOST: ${{ secrets.VM_HOST }}
          VM_USER: ${{ secrets.VM_USER }}
        run: |
          set -euo pipefail
          ssh -i ~/.ssh/id_ed25519 "${VM_USER}@${VM_HOST}" bash -lc '
            set -euo pipefail
            cd ~/mlops-spam-gcp
            git pull --rebase
            if [ -f .venv/bin/activate ]; then . .venv/bin/activate; fi
            python3 tools/export_metrics_for_pages.py
            echo "[VM] created:" && ls -lh docs/metrics.json || true
          '

      - name: Copy metrics.json from VM to runner
        env:
          VM_HOST: ${{ secrets.VM_HOST }}
          VM_USER: ${{ secrets.VM_USER }}
        run: |
          set -euo pipefail
          mkdir -p site
          scp -i ~/.ssh/id_ed25519 "${VM_USER}@${VM_HOST}:~/mlops-spam-gcp/docs/metrics.json" site/metrics.json
          echo "[Runner] preview of copied file:"
          head -c 200 site/metrics.json || true

      - name: Commit & push if changed
        run: |
          if ! git diff --quiet -- site/metrics.json; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add site/metrics.json
            git commit -m "metrics: daily auto-update"
            git push
          else
            echo "No changes in site/metrics.json"
          fi
