name: Update metrics.json (daily)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "5 3 * * *"   # 03:05 UTC täglich

permissions:
  contents: write

concurrency:
  group: pages-metrics
  cancel-in-progress: false

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Install ssh client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Setup SSH key
        env:
          VM_KNOWN: ${{ secrets.SSH_KNOWN_HOSTS || '' }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          if [ -n "$VM_KNOWN" ]; then
            echo "$VM_KNOWN" > ~/.ssh/known_hosts
          else
            ssh-keyscan -H "${{ secrets.VM_HOST }}" >> ~/.ssh/known_hosts
          fi

      - name: Run export on VM
        env:
          VM_HOST: ${{ secrets.VM_HOST }}
          VM_USER: ${{ secrets.VM_USER }}
        run: |
          ssh -i ~/.ssh/id_ed25519 "${VM_USER}@${VM_HOST}" bash -lc '
            set -euo pipefail
            cd ~/mlops-spam-gcp
            # sauberes Repo (ohne ungestagte Änderungen)
            git fetch origin main || true
            git reset --hard origin/main
            git clean -fd
            [ -f .venv/bin/activate ] && . .venv/bin/activate
            python3 tools/export_metrics_for_pages.py
            ls -lh docs/metrics.json || true
          '

      - name: Download metrics.json from VM
        env:
          VM_HOST: ${{ secrets.VM_HOST }}
          VM_USER: ${{ secrets.VM_USER }}
        run: |
          scp -i ~/.ssh/id_ed25519 "${VM_USER}@${VM_HOST}:~/mlops-spam-gcp/docs/metrics.json" ./metrics.json
          test -f .nojekyll || echo > .nojekyll   # sicherstellen, dass Pages nicht jekyllt

      - name: Commit & push if changed (gh-pages)
        run: |
          if ! git diff --quiet -- metrics.json; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add metrics.json .nojekyll
            git commit -m "metrics: daily auto-update"
            git push
          else
            echo "No changes in metrics.json"
          fi
